### ISSUE TITLE
(catbot-setup) IPC Panel Crashes When Trying to Start Bot(s) 

### ISSUE THREAD

**Issue by tobiashagen7** [explowz/cathook#23]
## System Information

**Distro:**  Arch<br>
**DE:**  KDE Plasma 5.27.2<br>
**Commit number:**  catbot-setup/d8351fce5eb91eff32d2677cb3f5b4bfb2e0f22d

### Starting the panel:
```
[cat@archlinux catbot-setup]$ ./start
~/Desktop/catbot-setup/cathook-ipc-web-panel ~/Desktop/catbot-setup
~/Desktop/catbot-setup
~/Desktop/catbot-setup/nullnexus-proxy ~/Desktop/catbot-setup
[PM2] Applying action restartProcessId on app [index](ids: [ 0 ])
[PM2] [index](0) ✓
[PM2] Process successfully started
┌─────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ index    │ default     │ 1.0.6   │ fork    │ 11852    │ 0s     │ 0    │ online    │ 0%       │ 8.8mb    │ cat      │ disabled │
└─────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
~/Desktop/catbot-setup
IPC Web Panel password: SIUwfxgD
Fixing NVIDIA crash
```
### Clicking "restart" on the bot after logging in and applying a quota:
```
node:internal/fs/utils:346
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/home/cat/Desktop/catbot-setup/user_instances/b0/.steam'
    at Object.realpathSync (node:fs:2570:7)
    at Bot.spawnSteam (/home/cat/Desktop/catbot-setup/cathook-ipc-web-panel/forever/bot.js:177:78)
    at Bot.update (/home/cat/Desktop/catbot-setup/cathook-ipc-web-panel/forever/bot.js:434:30)
    at BotManager.update (/home/cat/Desktop/catbot-setup/cathook-ipc-web-panel/forever/botmanager.js:34:19)
    at listOnTimeout (node:internal/timers:568:17)
    at process.processTimers (node:internal/timers:511:7) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/home/cat/Desktop/catbot-setup/user_instances/b0/.steam'
}

Node.js v19.7.0
```
(Panel is hung here, and refreshing the browser will redirect to an "Unable to connect" page.)

## Description

Catbot web panel crashes only after applying a quota and trying to (re)start the bots. 
There are no printed warnings between starting the panel and the crash.

## Steps to reproduce

- [x] I am able to consistently reproduce this error

Cathook (this fork with latest commit [cf19055](https://github.com/explowz/cathook/commit/cf1905585ce4f0085d6ce6a4ca92c13cfb75b7db)) was previously installed before running the catbot-setup.

1. Run `install-catbots` shell script on fresh-install of Arch.
2. Start panel with included `./start` script
3. Navigate to panel at http://localhost:8081/ and log-in to the control panel
5. Enter and apply a quota and click the "Restart" button
6. Click "Restart" and error is printed in terminal. (Panel is unavailable when browser window is refreshed.)

Both restart buttons in the control panel popup and button next to the bot instance name will crash the web panel.

## Checklist

- [x] I have included my DE / WM, and commit number. 
- [x] I have included the steps to reproduce and my logs to the best I am able to share.

**Comment by iOEMP** [comment]
known issue, probably won't be fixed, thanks for stopping by.

**Comment by tobiashagen7** [comment]
Makes sense, thanks.
