### ISSUE TITLE
Cathook bots and GUI crash when near a Tank in MVM

### ISSUE THREAD

**Issue by snipergaming888** [explowz/cathook#28]
(1)Sydney left the game ((1)Sydney timed out) | error that is reported on GUI
Sydney left the game (Client left game (Steam auth ticket has been canceled)
)
error that is reported on bots.
I haven't tested if it happens with nullworks, but it probably does.
GUI log:
`/home/sydney/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh: line 72: 28901 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game process removed: AppID 440 "/home/sydney/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=440 -- /home/sydney/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/sydney/.local/share/Steam/steamapps/common/Team Fortress 2/hl2.sh' -game tf -steam -windowed -w 640 -h 480 -novid -nojoy", ProcID 28901 
ThreadGetProcessExitCode: no such process 28901
ThreadGetProcessExitCode: no such process 28900
ThreadGetProcessExitCode: no such process 28898
Game 440 created interface STEAMAPPLIST_INTERFACE_VERSION001 / 
Game 440 created interface STEAMAPPS_INTERFACE_VERSION008 / 
Game 440 created interface STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
Game 440 created interface STEAMHTTP_INTERFACE_VERSION003 / 
Game 440 created interface STEAMHTTP_INTERFACE_VERSION003 / HTTP
Game 440 created interface STEAMINVENTORY_INTERFACE_V003 / 
Game 440 created interface STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
Game 440 created interface STEAMMUSIC_INTERFACE_VERSION001 / 
Game 440 created interface STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
Game 440 created interface STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
Game 440 created interface STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
Game 440 created interface STEAMUGC_INTERFACE_VERSION015 / 
Game 440 created interface STEAMUSERSTATS_INTERFACE_VERSION011 / UserStats
Game 440 created interface STEAMUSERSTATS_INTERFACE_VERSION012 / 
Game 440 created interface STEAMVIDEO_INTERFACE_V002 / 
Game 440 created interface SteamController008 / 
Game 440 created interface SteamFriends017 / 
Game 440 created interface SteamGameCoordinator001 / 
Game 440 created interface SteamGameStats001 / 
Game 440 created interface SteamInput003 / 
Game 440 created interface SteamMatchGameSearch001 / 
Game 440 created interface SteamMatchMaking009 / 
Game 440 created interface SteamMatchMakingServers002 / 
Game 440 created interface SteamNetworking006 / 
Game 440 created interface SteamNetworkingSockets009 / 
Game 440 created interface SteamNetworkingSocketsSerialized005 / 
Game 440 created interface SteamUser018 / User
Game 440 created interface SteamUser021 / 
Game 440 created interface SteamUser021 / User
Game 440 created interface SteamUtils002 / Utils
Game 440 created interface SteamUtils010 / 
Game 440 created interface SteamUtils010 / Utils
Game 440 method call count for IClientNetworkingUtilsSerialized::GotLocationString : 2
Game 440 method call count for IClientNetworkingSocketsSerialized::GetSTUNServer : 4
Game 440 method call count for IClientNetworkingSocketsSerialized::GetCachedRelayTicketCount : 1
Game 440 method call count for IClientControllerSerialized::GetAnalogActionHandle : 2
Game 440 method call count for IClientControllerSerialized::GetDigitalActionHandle : 49
Game 440 method call count for IClientControllerSerialized::GetActionSetHandle : 4
Game 440 method call count for IClientUGC::GetSubscribedItems : 1
Game 440 method call count for IClientUGC::GetNumSubscribedItems : 1
Game 440 method call count for IClientAudio::GetVoiceOptimalSampleRate : 1
Game 440 method call count for IClientAudio::StopVoiceRecording : 4
Game 440 method call count for IClientHTTP::ReleaseHTTPRequest : 4
Game 440 method call count for IClientHTTP::GetHTTPResponseBodyData : 4
Game 440 method call count for IClientHTTP::GetHTTPResponseBodySize : 1
Game 440 method call count for IClientHTTP::SendHTTPRequest : 4
Game 440 method call count for IClientHTTP::SetHTTPRequestHeaderValue : 3
Game 440 method call count for IClientHTTP::CreateHTTPRequest : 4
Game 440 method call count for IClientGameStats::AddRowAttributeInt64 : 38
Game 440 method call count for IClientGameStats::CommitRow : 14
Game 440 method call count for IClientGameStats::AddNewRow : 14
Game 440 method call count for IClientGameStats::AddRowAttributeFloat : 12
Game 440 method call count for IClientGameStats::AddRowAttributeString : 25
Game 440 method call count for IClientGameStats::AddRowAttributeInt : 75
Game 440 method call count for IClientGameStats::GetNewSession : 1
Game 440 method call count for IClientGameCoordinator::RetrieveMessage : 813
Game 440 method call count for IClientGameCoordinator::IsMessageAvailable : 1627
Game 440 method call count for IClientGameCoordinator::SendMessage : 743
Game 440 method call count for IClientConfigStore::GetString : 3
Game 440 method call count for IClientConfigStore::GetInt : 3
Game 440 method call count for IClientRemoteStorage::SetCloudEnabledForApp : 1
Game 440 method call count for IClientRemoteStorage::IsCloudEnabledForApp : 1
Game 440 method call count for IClientRemoteStorage::GetQuota : 2
Game 440 method call count for IClientRemoteStorage::FileExists : 3
Game 440 method call count for IClientRemoteStorage::GetFileSize : 1
Game 440 method call count for IClientRemoteStorage::FileRead : 1
Game 440 method call count for IClientRemoteStorage::FileWrite : 2
Game 440 method call count for IClientUserStats::GetDownloadedLeaderboardEntry : 2
Game 440 method call count for IClientUserStats::DownloadLeaderboardEntries : 13
Game 440 method call count for IClientUserStats::GetLeaderboardEntryCount : 11
Game 440 method call count for IClientUserStats::FindLeaderboard : 96
Game 440 method call count for IClientUserStats::SetAchievement : 5
Game 440 method call count for IClientUserStats::GetAchievement : 525
Game 440 method call count for IClientUserStats::StoreStats : 74
Game 440 method call count for IClientUserStats::SetStat : 2467
Game 440 method call count for IClientUserStats::GetStat : 739
Game 440 method call count for IClientUserStats::RequestCurrentStats : 1
Game 440 method call count for IClientAppManager::GetCurrentLanguage : 6
Game 440 method call count for IClientAppManager::GetLaunchCommandLine : 2
Game 440 method call count for IClientAppManager::GetAppStateInfo : 1
Game 440 method call count for IClientAppManager::BIsDlcEnabled : 1
Game 440 method call count for IClientAppManager::GetAvailableLanguages : 1
Game 440 method call count for IClientMatchmaking::ReleaseGMSQuery : 2
Game 440 method call count for IClientMatchmaking::GetGMSQueryResults : 2
Game 440 method call count for IClientMatchmaking::PollGMSQuery : 35
Game 440 method call count for IClientMatchmaking::BeginGMSQuery : 2
Game 440 method call count for IClientMatchmaking::GetLobbyOwner : 2
Game 440 method call count for IClientMatchmaking::AddFavoriteGame : 4
Game 440 method call count for IClientMatchmaking::GetFavoriteGameCount : 5
Game 440 method call count for IClientUtils::RecordSteamInterfaceCreation : 176
Game 440 method call count for IClientUtils::FilterText : 234627
Game 440 method call count for IClientUtils::InitFilterText : 1
Game 440 method call count for IClientUtils::IsSteamChina : 1
Game 440 method call count for IClientUtils::GetLauncherType : 1
Game 440 method call count for IClientUtils::SetAPICallResultWithoutPostingCallback : 1
Game 440 method call count for IClientUtils::AllocPendingAPICallHandle : 1
Game 440 method call count for IClientUtils::GetAPICallResult : 114
Game 440 method call count for IClientUtils::GetAppID : 198
Game 440 method call count for IClientUtils::GetImageRGBA : 29
Game 440 method call count for IClientUtils::GetImageSize : 29
Game 440 method call count for IClientUtils::GetIPCountry : 1
Game 440 method call count for IClientUtils::GetServerRealTime : 128
Game 440 method call count for IClientFriends::GetFriendPersonaName_Public : 2308
Game 440 method call count for IClientFriends::GetFriendRichPresence : 21
Game 440 method call count for IClientFriends::SetRichPresence : 121868
Game 440 method call count for IClientFriends::RequestUserInformation : 30
Game 440 method call count for IClientFriends::GetFriendGamePlayed : 10
Game 440 method call count for IClientFriends::GetFriendByIndex : 25
Game 440 method call count for IClientFriends::GetFriendCount : 25
Game 440 method call count for IClientFriends::GetMediumFriendAvatar : 19
Game 440 method call count for IClientFriends::GetSmallFriendAvatar : 10
Game 440 method call count for IClientFriends::GetFriendPersonaState : 28
Game 440 method call count for IClientFriends::GetFriendRelationship : 27
Game 440 method call count for IClientFriends::HasFriend : 660
Game 440 method call count for IClientFriends::GetPersonaName : 186
Game 440 method call count for IClientUser::BIsSubscribedApp : 1
Game 440 method call count for IClientUser::AdvertiseGame : 5
Game 440 method call count for IClientUser::CancelAuthTicket : 2
Game 440 method call count for IClientUser::GetAuthSessionTicket : 3
Game 440 method call count for IClientUser::GetSteamID : 6673
Game 440 method call count for IClientUser::BLoggedOn : 159
Uploaded AppInterfaceStats to Steam
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found

(process:28909): GLib-GObject-CRITICAL **: 13:11:40.707: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
src/steamexe/main.cpp (255) : Assertion Failed: reaping pid: 28909 -- gameoverlayui

src/steamexe/main.cpp (255) : Assertion Failed: reaping pid: 28909 -- gameoverlayui

sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
`

**Comment by snipergaming888** [comment]
i sent a log idk if its a segfault log

**Comment by snipergaming134** [comment]
you have the same name but different numbers thats funny lol

**Comment by snipergaming888** [comment]
Ight imma do that when I get home.

**Comment by snipergaming888** [comment]
> The shared library you sent was not build in Debug mode, meaning that it's not useful.

;literally built it in debug but ok
i will send it when i have time

**Comment by snipergaming888** [comment]
Awesome, I will test it when I have the time.

**Comment by snipergaming888** [comment]
I cloned the update into my catbot-setup folder (deleting original cathook folder). it seems that is is not fixed, as they crashed again.

**Comment by snipergaming888** [comment]
> Also, if you're using your fokred version, then don't forget to sync it, or just use my repository.

I am using yours, I will send the stuff again when I get the chance.

**Comment by snipergaming888** [comment]
> You're either not using this repository, or this crash is not due to something I have power over. The crash seems to be due to a vector function in the source-sdk-2013-headers, which is written by Valve, not by me, although I'm not seeing how that specific line of code could in any way crash the game. Please, provide specific details on how this crash can be replicated, so that I may test it myself.

Play Mann VS. machine on mvm_bigrock
I don't know if this is why they crash, but one crashed when the engineer bot spawned in. other than that crashes are just random.

**Comment by snipergaming888** [comment]
This is probably fixed.
