### ISSUE TITLE
Snipers holding the Hitman's Heatmaker never activate the abillity.

### ISSUE THREAD

**Issue by snipergaming888** [explowz/cathook#40]
## System Information

Arch linux, XFCE4,
1 Commit behind (the one where voting was fixed)

## Config used
https://drive.google.com/file/d/12Mh8klgJYaZtCA7vUqiCULLHac1upIcc/view?usp=sharing

## Description

Snipers holding the hitman's heatmaker will not activate their ability. I am using a strange one from the market.

## Steps to reproduce

Give a sniper a strange hitman's heatmaker.

## Additional information
Aimbot.autoshoot.activate-heatmaker is set to true.
IM A RETARD AND DIDNT PUT aimbot.autoshoot.activate.heatmaker=true IN THE CONFIG I SENT. it is on in my config.

**Comment by snipergaming888** [comment]
i missspelled it

**Comment by rosne-gamingyt** [comment]
k
